name: Compilazione Automatica APK

on:
  push:
    branches: [ main, master ] # Si attiva ogni volta che aggiorni il codice
  workflow_dispatch: # Ti permette di avviare la compilazione a mano con un click

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Scarica il codice dalla tua repository
      - name: Checkout del codice
        uses: actions/checkout@v4

      # 2. Configura l'ambiente Java (Richiesto da Android)
      - name: Configura Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Configura l'SDK di Flutter aggiornato (Risolve il problema di Dart SDK)
      - name: Configura Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.x' # Aggiornato per sbloccare just_audio e audio_session
          channel: 'stable'
          cache: true

      # 4. Scarica i pacchetti inseriti nel pubspec.yaml
      - name: Installa dipendenze (Pub Get)
        run: flutter pub get

      # 5. Compila l'APK in modalità Release
      - name: Compilazione APK Release
        run: flutter build apk --release

      # 6. Salva l'APK finale per poterlo scaricare
      - name: Carica l'APK nei file scaricabili
        uses: actions/upload-artifact@v4
        with:
          name: Auto-Launcher-APK
          path: build/app/outputs/flutter-apk/app-release.apk
