name: Compilazione Automatica APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del codice
        uses: actions/checkout@v4

       Sir- name: Configura Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Configura Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Installa dipendenze (Pub Get)
        run: flutter pub get

      # Aggiunto il flag --android-skip-build-dependency-validation per saltare i controlli rigidi delle versioni Gradle
      - name: Compilazione APK Release
        run: flutter build apk --release --android-skip-build-dependency-validation

      - name: Carica l'APK nei file scaricabili
        uses: actions/upload-artifact@v4
        with:
          name: Auto-Launcher-APK
          path: build/app/outputs/flutter-apk/app-release.apk
